# Project By : Eash Srivastava
# Domain : Data Science 
# Task 5 : Credit Card Fraud Detection

In [1]:
# Loading the libraries
import numpy as np
import pandas as pd 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [1]:
# Loading the DataFrame
import kagglehub
import pandas as pd
import os

# Download dataset from Kaggle
path = kagglehub.dataset_download("mlg-ulb/creditcardfraud")

print("Dataset path:", path)

# Load the CSV file
df = pd.read_csv(os.path.join(path, "creditcard.csv"))

# Preview data
df.head()

Downloading to C:\Users\Eash\.cache\kagglehub\datasets\mlg-ulb\creditcardfraud\3.archive...

100%|█████████████████████████████████████████████████████████████████████████████| 66.0M/66.0M [00:06<00:00, 11.3MB/s]

Extracting files...

Dataset path: C:\Users\Eash\.cache\kagglehub\datasets\mlg-ulb\creditcardfraud\versions\3

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
# Printing the first five rows
df.head()

   Time        V1        V2        V3        V4        V5  ...       V25       V26       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  ...  0.128539 -0.189115  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018  ...  0.167170  0.125895 -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  ... -0.327642 -0.139097 -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  ...  0.647376 -0.221929  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  ... -0.206010  0.502292  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [5]:
# Information about the data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [6]:
# Checking for missing values
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [7]:
# Distribution of legit and fradulent transaction
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

This dataset is highly unbalanced

0 --> Normal Transaction
1 --> Fradulen Transaction

In [9]:
# Seprating the data
legit = df[df.Class == 0]
fraud = df[df.Class == 1]

In [10]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [11]:
# Statistical Measures for Amount
df.Amount.describe()

count    284807.000000
mean         88.349619
std         250.120109
min           0.000000
25%           5.600000
50%          22.000000
75%          77.165000
max       25691.160000
Name: Amount, dtype: float64

In [12]:
#Compare the values of both the transaction
df.groupby('Class').mean()

               Time        V1        V2        V3        V4  ...       V25       V26       V27       V28      Amount
Class                                                        ...
0      94838.202258  0.008258 -0.006271  0.012171 -0.007860  ... -0.000072 -0.000089 -0.000295 -0.000131   88.291022
1      80746.806911 -4.771948  3.623778 -7.033281  4.542029  ...  0.041449  0.051648  0.170575  0.075667  122.211321

[2 rows x 30 columns]

Under-Sampling

In [16]:
# Taking teh random sample from the legit one to make th edatset balanced
legit_sample = legit.sample(n=492)

In [18]:
# Creating a new dtaset by concatenating the two 
new_df = pd.concat([legit_sample,fraud],axis=0)

In [19]:
new_df.Class.value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [21]:
# Spliting the dataset
X = new_df.drop(columns=['Class'],axis=1)
y = new_df['Class']

In [22]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

#### Model Trainig

In [23]:
model = LogisticRegression()
model.fit(X_train,y_train)

C:\Users\Eash\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

#### Model Evaluation

In [24]:
#Accuracy on the training data
y_pred_train = model.predict(X_train)
train_accuracy = accuracy_score(y_pred_train,y_train)
print("Traing Accuracy : ",train_accuracy)

Traing Accuracy :  0.9339263024142312

In [25]:
#Accuracy on the Test data
y_pred_test = model.predict(X_test)
test_accuracy = accuracy_score(y_pred_test,y_test)
print("Traing Accuracy : ",test_accuracy)

Traing Accuracy :  0.9543147208121827